version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: ziveitprojekty_elastic
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    links:
      - elastic
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: ziveitprojekty_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200/
    ports:
      - 5601:5601

  heartbeat:
    user: heartbeat
    build:
      context: ./docker/heartbeat
      dockerfile: Dockerfile

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    volumes:
      - ./api/logs:/logs
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
    depends_on:
      - elastic

#  elastalert:
#    volumes:
#      - ./elastalert/rules:/usr/src/app/rules
#    build:
#      context: ./elastalert
#      dockerfile: Dockerfile-production
#    network_mode: host

  api:
    links:
      - elastic
    image: node:12
    container_name: ziveitprojekty_api
    environment:
      - API_PORT=10000
      - ELASTIC_CLIENT_NODE=http://elastic:9200
      - ELASTIC_INDEX_NAME=ziveitprojekty
      - NODE_ENV=production
    ports:
      - 10000:10000
    volumes:
      - ./api:/usr/src/service
    working_dir: /usr/src/service
    command: npm start
    tty: true
